@startuml
title Диаграмма деятельности\n"Получение прогноза цены авиабилета"

start

:Ввод параметров перелёта;

:Отправка запроса;

:Проверка данных;
if (Данные корректны?) then (да)

  :Подготовка данных;
  :Передача в ML модель;
  :Расчёт цены;

  :Сохранение результата;
  :Отображение пользователю;

else (нет)
  :Сообщение об ошибке;
endif

stop
@enduml